### PR TITLE
Get numeral from npm instead of Bower

### PR DESCRIPTION
**Pull request by josemarluedke**
Implements #73.

### CODE REVIEW

**Comment by josemarluedke** [comment]
ping @thriqon.

**Comment by thriqon** [comment]
Great, I like it!

Will release it ASAP.

**Comment by josemarluedke** [comment]
@thriqon you mind releasing a new version to NPM containing this?

**Comment by thriqon** [comment]
It is done: https://www.npmjs.com/package/ember-cli-format-number

**Pull request merged**
